package com.agustin.videoboostao

import android.content.Context

/**
 * Apps "sensibles" que bloquean cualquier servicio de accesibilidad activo
 * (bancos, fintech, wallets, autenticadores, gestores de contrasenas). Cuando
 * una pasa a primer plano, el servicio se apaga solo (`disableSelf()`) para no
 * disparar ese bloqueo.
 *
 * Dos fuentes:
 * - [BUILTIN]: lista integrada con bancos de TODOS los paises donde se vende el
 *   Pixel oficialmente + apps sensibles globales (crypto/fintech/autenticadores).
 *   Cada package se verifico contra la URL de Google Play (parametro id=).
 * - Set del usuario (Prefs): apps que el usuario agrega manualmente desde la UI.
 *
 * Regenerada con investigacion; ver scratchpad/bank-packages.txt.
 */
object SensitiveApps {

    fun isSensitive(context: Context, pkg: String): Boolean =
        pkg in BUILTIN || pkg in Prefs.sensitiveUserApps(context)

    /** Prefijos con nombre de banco muy distintivo (cubre variantes regionales). */
    private val PREFIXES = listOf(
        "com.nu.",
        "com.bbva",
        "com.santander",
        "mx.bancosantander",
        "com.banorte",
        "com.citibanamex",
        "com.hsbc.hsbc",
        "com.scotiabank",
        "com.revolut",
    )

    fun isSensitiveByPrefix(pkg: String): Boolean = PREFIXES.any { pkg.startsWith(it) }

    // Lista integrada (verificada via Google Play). Ordenada por package.
    val BUILTIN: Set<String> = setOf(
        "aib.ibank.android",  // AIB (Ireland)
        "air.app.scb.breeze.android.main.sg.prod",  // Standard Chartered (Singapore)
        "at.erstebank.george",  // Erste/Sparkasse George (Austria)
        "at.rsg.pfp",  // Raiffeisen Mein ELBA (Austria)
        "at.volksbank.volksbankmobile",  // Volksbank (Austria)
        "au.com.bank86400",  // Ubank (Australia)
        "au.com.bankwest.mobile",  // Bankwest (Australia)
        "au.com.ingdirect.android",  // ING (Australia)
        "au.com.nab.mobile",  // NAB (Australia)
        "be.argenta.bankieren",  // Argenta (Belgium)
        "be.belfius.directmobile.android",  // Belfius (Belgium)
        "be.crelan.channels.mobile.android.store",  // Crelan (Belgium)
        "br.com.bb.android",  // Banco do Brasil (Brazil)
        "br.com.intermedium",  // Banco Inter (Brazil)
        "br.gov.caixa.tem",  // Caixa Tem (Brazil)
        "brd.bankingapp.android",  // BRD (Romania)
        "bvm.bvmapp",  // Knab (Netherlands)
        "ca.bnc.android",  // National Bank (Canada)
        "ca.mobile.explorer",  // Crédito Agrícola (Portugal)
        "ca.tangerine.clients.banking.app",  // Tangerine (Canada)
        "cgd.pt.caixadirectaparticulares",  // Caixa Geral (Portugal)
        "ch.bcv.mobile.android",  // BCV (Switzerland)
        "ch.postfinance.android",  // PostFinance (Switzerland)
        "ch.raiffeisen.android",  // Raiffeisen (Switzerland)
        "ch.zkb.slv.mobile.client.android",  // ZKB (Switzerland)
        "co.infinum.nlb",  // NLB (Slovenia)
        "co.mona.android",  // Crypto.com
        "co.uk.Nationwide.Mobile",  // Nationwide (UK)
        "co.uk.getmondo",  // Monzo
        "com.TMBTOUCH.PRODUCTION",  // ttb touch (Thailand)
        "com.abnamro.nl.mobile.payments",  // ABN AMRO (Netherlands)
        "com.ally.MobileBanking",  // Ally (US)
        "com.ambank.ambankonline",  // AmBank (Malaysia)
        "com.anz.android.gomoney",  // ANZ (Australia)
        "com.anz.lotus",  // ANZ Plus (Australia)
        "com.authy.authy",  // Authy
        "com.axis.mobile",  // Axis (India)
        "com.azure.authenticator",  // Microsoft Authenticator
        "com.bancomer.mbanking",  // BBVA Mexico (Mexico)
        "com.bankaustria.android.olb",  // Bank Austria UniCredit (Austria)
        "com.bankinter.launcher",  // Bankinter (Spain)
        "com.bankofireland.mobilebanking",  // Bank of Ireland (Ireland)
        "com.barclays.android.barclaysmobilebanking",  // Barclays (UK)
        "com.bawagpsk.bawagpsk",  // BAWAG (Austria)
        "com.bbl.mobilebanking",  // Bangkok Bank (Thailand)
        "com.bbva.bbvacontigo",  // BBVA (Mexico/Spain)
        "com.bca",  // BCA (Indonesia)
        "com.bendigobank.mobile",  // Bendigo (Australia)
        "com.binance.dev",  // Binance
        "com.bmo.mobile",  // BMO (Canada)
        "com.bnpp.easybanking",  // BNP Paribas Fortis (Belgium)
        "com.bochk.app.aos",  // BOCHK (Hong Kong)
        "com.boursorama.android.clients",  // BoursoBank (France)
        "com.bpi.ng.app",  // BPI (Philippines)
        "com.bradesco",  // Bradesco (Brazil)
        "com.bunq.android",  // bunq (Netherlands)
        "com.bybit.app",  // Bybit
        "com.c6bank.app",  // C6 Bank (Brazil)
        "com.caisseepargne.android.mobilebanking",  // Caisse d'Épargne (France)
        "com.callpod.android_apps.keeper",  // Keeper
        "com.cathaybk.mymobibank.android",  // Cathay United (Taiwan)
        "com.chase.sig.android",  // Chase (US)
        "com.chinatrust.mobilebank",  // CTBC (Taiwan)
        "com.cibc.android.mobi",  // CIBC (Canada)
        "com.cimb.cimbocto",  // CIMB OCTO (Malaysia)
        "com.citi.citimobile",  // Citi (US)
        "com.citibanamex.banamexmobile",  // Citibanamex (Mexico)
        "com.citibank.mobile.hk",  // Citibank (Hong Kong)
        "com.citizensbank.androidapp",  // Citizens (US)
        "com.clairmail.fth",  // Fifth Third (US)
        "com.coinbase.android",  // Coinbase
        "com.commbank.netbank",  // CommBank (Australia)
        "com.csam.icici.bank.imobile",  // ICICI iMobile (India)
        "com.current.app",  // Current
        "com.danskebank.mobilebank3.dk",  // Danske Bank (Denmark)
        "com.danskebank.mobilebank3.fi",  // Danske Bank (Finland)
        "com.dashlane",  // Dashlane
        "com.db.pwcc.dbmobile",  // Deutsche Bank (Germany)
        "com.dbs.dbspaylah",  // DBS PayLah (Singapore)
        "com.dbs.hk.iwealthhk",  // DBS (Hong Kong)
        "com.dbs.sg.dbsmbanking",  // DBS (Singapore)
        "com.desjardins.mobile",  // Desjardins (Canada)
        "com.digitalfemsa_spinplus",  // Spin by OXXO (Mexico)
        "com.discoverfinancial.mobile",  // Discover (US)
        "com.dkbcodefactory.banking",  // DKB (Germany)
        "com.duosecurity.duomobile",  // Duo Mobile
        "com.eqbank.eqbank",  // EQ Bank (Canada)
        "com.esunbank",  // E.Sun (Taiwan)
        "com.fineco.it",  // Fineco (Italy)
        "com.fisglobal.d1obmobile",  // Oriental Bank (Puerto Rico)
        "com.fubon.aibank",  // Taipei Fubon (Taiwan)
        "com.fullsix.android.labanquepostale.accountaccess",  // La Banque Postale (France)
        "com.globe.gcash.android",  // GCash (Philippines)
        "com.gojek.gopay",  // GoPay (Indonesia)
        "com.google.android.apps.authenticator2",  // Google Authenticator
        "com.google.android.apps.nbu.paisa.user",  // Google Pay India (India)
        "com.grabtaxi.passenger",  // Grab/GrabPay (SG/MY)
        "com.grppl.android.shell.CMBlloydsTSB73",  // Lloyds (UK)
        "com.grppl.android.shell.halifax",  // Halifax (UK)
        "com.hanabank.oqf",  // Hana 1Q (Korea)
        "com.handelsbanken.mobile.android",  // Handelsbanken (Sweden)
        "com.hangseng.rbmobile",  // Hang Seng (Hong Kong)
        "com.hdfcbank.android.now",  // HDFC new (India)
        "com.hey.banco",  // Hey Banco (Mexico)
        "com.inbursa.client",  // Inbursa (Mexico)
        "com.infonow.bofa",  // Bank of America (US)
        "com.ing.banking",  // ING (Belgium)
        "com.ing.mobile",  // ING (Netherlands)
        "com.itau",  // Itaú (Brazil)
        "com.jkos.app",  // JKoPay (Taiwan)
        "com.kakaobank.channel",  // KakaoBank (Korea)
        "com.kasikorn.retail.mbanking.wap",  // K PLUS (Thailand)
        "com.kbc.mobile.android.phone.kbc",  // KBC (Belgium)
        "com.kbstar.kbbank",  // KB Kookmin (Korea)
        "com.key.android",  // KeyBank (US)
        "com.konylabs.capitalone",  // Capital One (US)
        "com.kraken.invest.app",  // Kraken
        "com.krungsri.kma",  // Krungsri (Thailand)
        "com.kubi.kucoin",  // KuCoin
        "com.lastpass.authenticator",  // LastPass Authenticator
        "com.latuabancaperandroid",  // Intesa Sanpaolo (Italy)
        "com.linepaytw.upay",  // LINE Pay (Taiwan)
        "com.luminorgroup.luminor",  // Luminor (Estonia)
        "com.lynxspa.bancopopolare",  // Banco BPM (Italy)
        "com.maybank2u.life",  // Maybank MAE (Malaysia)
        "com.mitake.android.bk.tcb",  // Taiwan Cooperative (Taiwan)
        "com.msf.kbank.mobile",  // Kotak (India)
        "com.mtel.androidbea",  // BEA (Hong Kong)
        "com.mufg.bk.applisp.app",  // MUFG (Japan)
        "com.navyfederal.android",  // Navy Federal (US)
        "com.nearform.ptsb",  // PTSB (Ireland)
        "com.neonbanking.app",  // Neon (Switzerland)
        "com.nordpass.android.app.password.manager",  // NordPass
        "com.nu.production",  // Nu (Mexico/Brazil)
        "com.ocbc.mobile",  // OCBC (Singapore)
        "com.octopuscards.nfc_reader",  // Octopus (Hong Kong)
        "com.onedebit.chime",  // Chime
        "com.onepassword.android",  // 1Password
        "com.paymaya",  // Maya (Philippines)
        "com.paypal.android.p2pmobile",  // PayPal
        "com.pbb.mypb",  // Public Bank MyPB (Malaysia)
        "com.pcfinancial.mobile",  // Simplii (Canada)
        "com.phonepe.app",  // PhonePe (India)
        "com.picpay",  // PicPay (Brazil)
        "com.pnc.ecommerce.mobile",  // PNC (US)
        "com.popular.android.mibanco",  // Banco Popular (Puerto Rico)
        "com.posteitaliane.spim",  // Poste Italiane (Italy)
        "com.rbc.mobile.android",  // RBC (Canada)
        "com.rbinternational.retail.mobileapp",  // Raiffeisen (Hungary)
        "com.rbs.mobile.android.natwest",  // NatWest (UK)
        "com.revolut.revolut",  // Revolut (global)
        "com.rhbgroup.rhbmobilebanking",  // RHB (Malaysia)
        "com.rietumu.ibank",  // Rietumu (Latvia)
        "com.santander.app",  // Santander (Brazil)
        "com.santander.enlace.BET",  // Santander Enlace (Mexico)
        "com.satispay.customer",  // Satispay (Italy)
        "com.sbi.lotusintouch",  // SBI YONO (India)
        "com.scb.breezebanking.hk",  // Standard Chartered (Hong Kong)
        "com.scb.phone",  // SCB EASY (Thailand)
        "com.scotiabank.banking",  // Scotiabank (Canada)
        "com.scotiabankmx.scotiamovil",  // Scotiabank Mexico (Mexico)
        "com.shinhan.sbanking",  // Shinhan SOL (Korea)
        "com.snapwork.hdfc",  // HDFC (India)
        "com.squareup.cash",  // Cash App
        "com.starfinanz.smob.android.sfinanzstatus",  // Sparkasse (Germany)
        "com.starlingbank.android",  // Starling (UK)
        "com.swedbank",  // Swedbank (Estonia)
        "com.tdbank",  // TD Bank (US)
        "com.transferwise.android",  // Wise
        "com.triodos.bankingnl",  // Triodos (Netherlands)
        "com.truist.mobile",  // Truist (US)
        "com.ubs.swidKXJ.android",  // UBS (Switzerland)
        "com.unicredit",  // UniCredit (Italy)
        "com.unionbankph.online",  // UnionBank (Philippines)
        "com.uob.mighty.app",  // UOB TMRW (Singapore)
        "com.usaa.mobile.android.usaa",  // USAA (US)
        "com.usbank.mobilebanking",  // U.S. Bank (US)
        "com.varomoney.bank",  // Varo
        "com.venmo",  // Venmo
        "com.wallet.crypto.trustapp",  // Trust Wallet
        "com.wf.wellsfargomobile",  // Wells Fargo (US)
        "com.willmobile.mobilebank.fcb",  // First Commercial (Taiwan)
        "com.wooribank.smart.npib",  // Woori WON (Korea)
        "com.x8bit.bitwarden",  // Bitwarden
        "com.yuh",  // Yuh (Switzerland)
        "com.zellepay.zelle",  // Zelle
        "com.zentity.pabk",  // Poštová/365.bank (Slovakia)
        "com.zentity.sbank.csobsk",  // ČSOB (Slovakia)
        "cz.airbank.android",  // Air Bank (Czechia)
        "cz.csas.georgego",  // Česká spořitelna George (Czechia)
        "cz.csob.smart",  // ČSOB Smart (Czechia)
        "cz.fio.sb2",  // Fio (Czechia)
        "cz.mbank",  // mBank (Czechia)
        "cz.moneta.smartbanka",  // Moneta (Czechia)
        "cz.rb.app.smartphonebanking",  // Raiffeisenbank (Czechia)
        "de.c24.bankapp",  // C24 Bank (Germany)
        "de.comdirect.app",  // Comdirect (Germany)
        "de.commerzbanking.mobil",  // Commerzbank (Germany)
        "de.fiduciagad.banking.vr",  // VR Banking (Germany)
        "de.ingdiba.bankingapp",  // ING (Germany)
        "de.number26.android",  // N26 (Germany/Austria)
        "de.postbank.finanzassistent",  // Postbank (Germany)
        "dk.danskebank.mobilepay",  // MobilePay (Denmark)
        "dk.jyskebank.mobilbank",  // Jyske (Denmark)
        "dk.nordea.mobilebank",  // Nordea (Denmark)
        "ee.cooppank.mbankapp",  // Coop Pank (Estonia)
        "ee.lhv.lhv",  // LHV (Estonia)
        "es.bancosantander.apps",  // Santander (Spain)
        "es.bizum.wallet",  // Bizum (Spain)
        "es.lacaixa.mobile.android.newwapicon",  // CaixaBank (Spain)
        "es.openbank.mobile",  // Openbank (Spain)
        "es.unicajabanco.app",  // Unicaja (Spain)
        "eu.inmite.prj.kb.mobilbank",  // Komerční banka (Czechia)
        "exodusmovement.exodus",  // Exodus
        "fi.danskebank.mobilepay",  // MobilePay (Finland)
        "fi.nordea.mobilebank",  // Nordea (Finland)
        "fi.op.android.opmobiili",  // OP (Finland)
        "fi.spankki",  // S-Pankki (Finland)
        "fr.banquepopulaire.cyberplus",  // Banque Populaire (France)
        "fr.bnpp.digitalbanking",  // Hello bank (France)
        "fr.creditagricole.androidapp",  // Crédit Agricole (France)
        "hk.alipay.wallet",  // AlipayHK (Hong Kong)
        "hk.com.hsbc.hsbchkmobilebanking",  // HSBC (Hong Kong)
        "hr.asseco.android.intesa.isbd.isps",  // Intesa SI (Slovenia)
        "hr.asseco.android.jimba.cecro",  // CEC (Romania)
        "hr.asseco.android.jimba.mUCI.hu",  // UniCredit (Hungary)
        "hu.khb",  // K&H (Hungary)
        "hu.mkb.mobilapp",  // MKB/MBH (Hungary)
        "hu.otpbank.mobile",  // OTP (Hungary)
        "id.bmri.livin",  // Livin Mandiri (Indonesia)
        "id.co.bri.brimo",  // BRImo (Indonesia)
        "id.dana",  // DANA (Indonesia)
        "in.org.npci.upiapp",  // BHIM (India)
        "io.metamask",  // MetaMask
        "it.gruppobper.ams.android.bper",  // BPER (Italy)
        "it.icbpi.mobile",  // Nexi Pay (Italy)
        "jp.co.japannetbank.smtapp.balance",  // PayPay Bank (Japan)
        "jp.co.jibunbank.jibunmain",  // au Jibun (Japan)
        "jp.co.mizuhobank.banking",  // Mizuho (Japan)
        "jp.co.rakuten_bank.rakutenbank",  // Rakuten Bank (Japan)
        "jp.co.smbc.direct",  // SMBC (Japan)
        "jp.japanpost.jp_bank.bankbookapp",  // Japan Post Bank (Japan)
        "jp.ne.paypay.android.app",  // PayPay (Japan)
        "ktbcs.netbank",  // Krungthai NEXT (Thailand)
        "libra.mobile.banking",  // Libra (Romania)
        "lt.apps.luminor",  // Luminor (Lithuania)
        "lt.sb.mobileapp",  // Artea/Šiaulių (Lithuania)
        "lt.swedbank.mobile",  // Swedbank (Lithuania)
        "lv.apps.luminor",  // Luminor (Latvia)
        "lv.citadele.mobile",  // Citadele (Latvia)
        "lv.swedbank.mobile",  // Swedbank (Latvia)
        "mobi.inthepocket.bcmc.bancontact",  // Payconiq/Bancontact (Belgium)
        "mobi.societegenerale.mobile.lappli",  // Société Générale (France)
        "mx.bancosantander.supermovil",  // Santander (Mexico)
        "mx.com.bancoazteca.bazdigitalmovil",  // Banco Azteca (Mexico)
        "mx.com.bancoppel.bancoppel",  // BanCoppel (Mexico)
        "mx.com.stori.app",  // Stori (Mexico)
        "mx.hsbc.hsbcmexico",  // HSBC Mexico (Mexico)
        "mx.klar.app",  // Klar (Mexico)
        "my.com.hongleongconnect.mobileconnect",  // Hong Leong (Malaysia)
        "my.com.myboost",  // Boost (Malaysia)
        "my.com.tngdigital.ewallet",  // Touch n Go (Malaysia)
        "net.bnpparibas.mescomptes",  // BNP Paribas (France)
        "net.inverline.bancosabadell.officelocator.android",  // Sabadell (Spain)
        "net.one97.paytm",  // Paytm (India)
        "nh.smart.banking",  // NH Nonghyup (Korea)
        "nl.devolksbank.asn.bankieren",  // ASN (Netherlands)
        "nl.devolksbank.regio.bankieren",  // Regiobank (Netherlands)
        "nl.devolksbank.sns.bankieren",  // SNS (Netherlands)
        "nl.rabomobiel",  // Rabobank (Netherlands)
        "no.apps.dnbnor",  // DNB (Norway)
        "no.dnb.vipps",  // Vipps (Norway)
        "no.nordea.mobilebank",  // Nordea (Norway)
        "no.sparebank1.mobilbank",  // SpareBank 1 (Norway)
        "nz.co.anz.android.mobilebanking",  // ANZ (New Zealand)
        "nz.co.asb.asbmobile",  // ASB (New Zealand)
        "nz.co.bnz.droidbanking",  // BNZ (New Zealand)
        "nz.co.cooperativebank",  // Co-operative (New Zealand)
        "nz.co.kiwibank.mobile",  // Kiwibank (New Zealand)
        "nz.co.westpac",  // Westpac (New Zealand)
        "org.microemu.android.model.common.VTUserApplicationBNRTMB",  // Banorte (Mexico)
        "org.westpac.bank",  // Westpac (Australia)
        "ovo.id",  // OVO (Indonesia)
        "pegasus.project.ebh.mobile.android.bundle.mobilebank",  // Erste (Hungary)
        "ph.com.bdo.retail",  // BDO (Philippines)
        "ph.com.metrobank.mcc.mbonline",  // Metrobank (Philippines)
        "piuk.blockchain.android",  // Blockchain.com
        "pl.aliorbank.aib",  // Alior (Poland)
        "pl.bzwbk.bzwbk24",  // Santander (Poland)
        "pl.ing.mojeing",  // ING Moje ING (Poland)
        "pl.mbank",  // mBank (Poland)
        "pl.pkobp.iko",  // PKO BP IKO (Poland)
        "pr.com.firstbank.app7",  // FirstBank (Puerto Rico)
        "pr.com.santander.icBanking.androidUI",  // Santander (Puerto Rico)
        "pt.bancobpi.mobile.fiabilizacao",  // BPI (Portugal)
        "pt.novobanco.nbsmarter",  // Novo Banco (Portugal)
        "pt.santander.oneappparticulares",  // Santander (Portugal)
        "pt.sibs.android.mbway",  // MB WAY (Portugal)
        "ro.bcr.georgego",  // BCR George (Romania)
        "ro.btrl.mobile",  // Banca Transilvania (Romania)
        "ro.ing.mobile.banking.android.activity",  // ING (Romania)
        "ro.raiffeisen.smartmobile",  // Raiffeisen (Romania)
        "se.bankgirot.swish",  // Swish (Sweden)
        "se.nordea.mobilebank",  // Nordea (Sweden)
        "se.seb.estonia",  // SEB (Estonia)
        "se.seb.latvia",  // SEB (Latvia)
        "se.seb.lithuania",  // SEB (Lithuania)
        "se.seb.privatkund",  // SEB (Sweden)
        "se.swedbank.mobil",  // Swedbank (Sweden)
        "sg.trust",  // Trust Bank (Singapore)
        "si.nkbm.bnk.android",  // Nova KBM (Slovenia)
        "sk.mbank",  // mBank (Slovakia)
        "sk.slsp.georgego",  // Slovenská sporiteľňa George (Slovakia)
        "sk.tb.ib.tatraandroid",  // Tatra banka (Slovakia)
        "sk.vub.mobile",  // VÚB (Slovakia)
        "softax.pekao.powerpay",  // Pekao PeoPay (Poland)
        "src.com.bni",  // BNI (Indonesia)
        "th.co.truemoney.wallet",  // TrueMoney (Thailand)
        "tsb.mobilebanking",  // TSB (New Zealand)
        "tw.com.megabank.mobilebank.pre",  // Mega (Taiwan)
        "tw.com.taishinbank.mobile",  // Taishin (Taiwan)
        "uk.co.hsbc.hsbcukmobilebanking",  // HSBC UK (UK)
        "uk.co.santander.santanderUK",  // Santander UK (UK)
        "viva.republica.toss",  // Toss (Korea)
        "wit.android.bcpBankingApp.activoBank",  // ActivoBank (Portugal)
        "wit.android.bcpBankingApp.millennium",  // Millennium bcp (Portugal)
        "wit.android.bcpBankingApp.millenniumPL",  // Millennium (Poland)
        "www.ingdirect.nativeframe",  // ING (Spain)
    )
}
